# Genetic Variation Prediction (Benign Or Pathogenic)

## Data Preprocessing

### Importing the Libraries

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Importing the dataset

In [ ]:
dataset=pd.read_csv('gene_var_1.csv')
X=dataset.iloc[:,1:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
print(X)

[[1 1168180 0.0771 ... 522 174 1]
 [1 1470752 0.0 ... 509 170 -1]
 [1 1737942 0.0 ... 239 80 -1]
 ...
 [1 55505647 0.0098 ... 137 46 1]
 [1 55505668 0.0958 ... 158 53 1]
 [1 55509689 0.0 ... 381 127 1]]


In [ ]:
print(y)

[0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0
 1 0 0 1 1 0 0 0 1 0 0]


### Redefining the coloumns

In [ ]:
print(X)

[[1 1168180 0.0771 ... 522 174 1]
 [1 1470752 0.0 ... 509 170 -1]
 [1 1737942 0.0 ... 239 80 -1]
 ...
 [1 55505647 0.0098 ... 137 46 1]
 [1 55505668 0.0958 ... 158 53 1]
 [1 55509689 0.0 ... 381 127 1]]


In [ ]:
dataset['Allele'].value_counts()

A    60
T    49
C    27
G    23
Name: Allele, dtype: int64

In [ ]:
X


In [ ]:
print(X[:,5])

[1 0 2 0 3 1 1 3 0 0 0 0 3 3 0 3 3 3 0 3 1 0 0 2 0 3 0 0 3 0 0 0 1 0 3 3 0
 0 3 1 3 0 1 0 3 1 0 2 2 0 3 3 3 2 3 0 3 3 0 1 3 2 2 3 1 1 3 2 0 3 3 3 1 0
 0 0 0 1 1 1 0 3 2 1 1 3 0 0 3 2 1 3 1 1 0 1 2 0 0 0 0 2 0 3 3 0 0 2 2 1 3
 2 0 2 0 2 3 1 1 0 2 0 0 3 0 3 0 3 0 3 0 3 0 1 0 2 3 3 0 3 0 1 0 3 3 2 0 3
 3 2 0 1 0 2 2 0 3 3 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 6] = le.fit_transform(X[:, 6])

In [ ]:
print(X[:,6])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 1 0 0 0 0 0 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 7] = le.fit_transform(X[:, 7])

In [ ]:
print(X[:,7])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 8] = le.fit_transform(X[:, 8])

In [ ]:
print(X[:,8])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(X[:,5:8])

[[1 0 0]
 [0 0 0]
 [2 0 0]
 [0 0 0]
 [3 0 0]
 [1 0 0]
 [1 0 0]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [3 0 0]
 [0 0 0]
 [3 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [2 0 0]
 [0 0 0]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [3 0 0]
 [1 0 0]
 [3 0 0]
 [0 0 0]
 [1 0 0]
 [0 0 0]
 [3 0 0]
 [1 0 0]
 [0 0 0]
 [2 0 0]
 [2 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [3 0 0]
 [2 0 0]
 [3 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [0 0 0]
 [1 0 0]
 [3 0 0]
 [2 0 0]
 [2 0 0]
 [3 0 0]
 [1 0 0]
 [1 0 0]
 [3 0 0]
 [2 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [3 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 0]
 [3 0 0]
 [2 0 0]
 [1 0 0]
 [1 0 0]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [3 0 0]
 [2 0 0]
 [1 0 0]
 [3 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [2 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [2 0 0]
 [0 0 0]
 [3 0 0]
 [3 0 0]
 [0 0 0]
 [0 0 0]
 [2 0 0]
 [2 0 0]
 [1 0 0]
 [3 0 0]
 

### Training and Testing of the dataset

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building ANN!

##Adding Layers

### Adding Input Layer

In [ ]:
ann=tf.keras.models.Sequential()

### Adding Hidden layer 1

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding Hidden Layer 2

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Final Output Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='sigmoid'))

## Compiling the ANN

In [ ]:
ann.compile(optimizer='adam',loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [ ]:
ann.fit(X_train, y_train, batch_size = 18, epochs = 100)

Epoch 1/100


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


8/8 [==============================] - 0s 2ms/step - loss: 1.7439 - accuracy: 0.2677
Epoch 2/100
8/8 [==============================] - 0s 2ms/step - loss: 1.7129 - accuracy: 0.3386
Epoch 3/100
8/8 [==============================] - 0s 2ms/step - loss: 1.6836 - accuracy: 0.3780
Epoch 4/100
8/8 [==============================] - 0s 2ms/step - loss: 1.6551 - accuracy: 0.4646
Epoch 5/100
8/8 [==============================] - 0s 2ms/step - loss: 1.6260 - accuracy: 0.5276
Epoch 6/100
8/8 [==============================] - 0s 2ms/step - loss: 1.5947 - accuracy: 0.5512
Epoch 7/100
8/8 [==============================] - 0s 2ms/step - loss: 1.5632 - accuracy: 0.6299
Epoch 8/100
8/8 [==============================] - 0s 2ms/step - loss: 1.5307 - accuracy: 0.6929
Epoch 9/100
8/8 [==============================] - 0s 2ms/step - loss: 1.4969 - accuracy: 0.7008
Epoch 10/100
8/8 [==============================] - 0s 2ms/step - loss: 1.4622 - accuracy: 0.7244
Epoch 11/100
8/8 [=======================

In [ ]:
y_pred = ann.predict(X_test)


In [ ]:
y_pred2 = []
answers = []
for i in y_pred:
    for j in i:
        if j>=0.5:
            y_pred2.append(1)
        else:
            y_pred2.append(0)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy: ",round(accuracy_score(y_test,y_pred2)*100,2),"%")

Accuracy:  84.38 %
